apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nsfi31j4r-nodejs 
  janus-idp.io/tekton: nsfi31j4r-nodejs
  backstage.io/kubernetes-id: nsfi31j4r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nsfi31j4r-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml